---
- name: NXOS exercise 3.2
  hosts: nxos
  tasks:
    - name: add new IP addresses
      nxos_l3_interface:
        provider: "{{ provider_nxapi }}"
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
        ipv6: "{{ item.ipv6 }}"
      with_items: "{{ ip_addresses }}"
      notify: write mem

  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy running startup
      changed_when: True
      tags: wr_mem

