---
- name: ios facts serial
  hosts: cisco
  vars:
    creds:
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      host: "{{ ansible_host }}"
  tasks: 
    - ios_facts:
        provider: "{{ creds }}"
      tags: facts_only
    
    - debug:
        var: ansible_net_serialnum

    - debug:
        msg: "SN :   {{ ansible_net_serialnum }}"

