---
- name: Simple Test with items
  hosts: local
  tasks:
    - name: with testing
      debug:
        msg: "{{ item }}"
      with_items:
        - 10.10.10.1
        - 10.10.20.1
        - 10.10.30.1
        - 10.10.40.1


