---
- name: When Testing
  hosts: local
  vars:
    my_str: whatever
    version: ""

  tasks:
    - name: Hard-coded to False
      debug:
        msg: Hello World is False
      when: False

    - name: Hard-coded to True
      debug:
        msg: Hello World is True
      when: True

    - name: Testing string equality
      debug:
        msg: whatever
      when: my_str != 'whatever'

    - name: Substring in larger string
      debug:
        msg: This is Cisco IOS
      when: "'Cisco IOS' in version"

    - name: This variable is defined
      debug:
        msg: Variable defined
      when: version is defined

    - command: /bin/false
      register: result
      ignore_errors: True

    # The previous form using a filter was deprecated
    - debug:
        msg: "Hello world"
      when: result is failed

