---
- name: Print out variables
  hosts: cisco
  vars:
    ntp_server_1: 20.20.20.20
    ntp_server_2: 20.20.20.30
  tasks:
    - debug:
        msg: "{{ inventory_hostname }}"
    - debug:
        msg: "{{ ansible_host }}"
    - debug:
        msg: "{{ local_as_number }}"
    - debug:
        msg: "{{ remote_as_number }}"
    - debug:
        msg: "{{ ntp_server_1 }}"
    - debug:
        msg: "{{ ntp_server_2 }}"

