---
- name: exercise 4 ios
  hosts: cisco
  gather_facts: true
  tasks:
    - name: snmp contact and location
      ios_config:
        provider: "{{ creds_ssh }}"
        lines: "{{ snmp_config }}"


