---
- name: napalm exercise 1
  hosts: cisco
  gather_facts: true
  tasks:
    - name: LLDP
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: "lldp_neighbors"

    - name: set LLDP 
      set_fact:
        lldp_info: "{{ ansible_facts['napalm_lldp_neighbors']['FastEthernet4'][0] }}"

    - name: assert neighbor
      assert:
        that:
          - lldp_info.hostname == "twb-sf-hpsw1"
          - lldp_info.port == "13"
        fail_msg: "LLDP neighbor not expected"
        success_msg: "LLDP neighbor is expected"

