---
- name: napalm exercise 1
  hosts: cisco
  gather_facts: true
  tasks:
    - name: LLDP
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
        filter: "lldp_neighbors"

    - name: set LLDP 
      set_fact:
        lldp_info: "{{ ansible_facts['napalm_lldp_neighbors']['FastEthernet4'][0] }}"

    - debug:
        var: lldp_info

    - name: set LLDP with
      set_fact:
         lldp_info_item: "{{ napalm_lldp_neighbors[item][0] }}"
      with_items: "{{ napalm_lldp_neighbors }}"

    - debug:
        var: lldp_info_item

